# Generated by Django 6.1.1 on 2026-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeoption',
            old_name='grade',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
